### PR TITLE
Suggestion: Each guild should maintain a charter, and elect a speaker

### PR DESCRIPTION
**Pull request by genexp**

### CODE REVIEW

**Comment by Shockem** [comment]
👍 🍰

**Comment by mattbanks** [comment]
A charter and elections seems a little too formal / bureaucratic, IMO. Maybe just call it a mission statement and have the team internally decide who is going to talk at team meetings?

**Comment by Shockem** [comment]
I agree with @mattbanks that the terminology seems too formal. I also think the team can decide who the speaker is but the role `Speaker` still exists, just up to the team on how they want to fill it.

**Comment by genexp** [comment]
Good points, ok, how is this change?

**Pull request merged**
